name:                 dataflow-project
version:              0.1.0.0
visibility:           public
id:                   dataflow-project-0.1.0.0-inplace
key:                  dataflow-project-0.1.0.0-inplace
license:              MIT
maintainer:           shpyliovyy@gmail.com
author:               SviatoslavShpylovyi
category:             Language
abi:                  inplace
exposed:              True
exposed-modules:      AST Errors Parser
import-dirs:
    "C:\\Project\\FP HOMEWORKD\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.8.2\\dataflow-project-0.1.0.0\\build"

library-dirs:
    "C:\\Project\\FP HOMEWORKD\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.8.2\\dataflow-project-0.1.0.0\\build"
    C:\msys64\mingw64\lib

library-dirs-static:
    "C:\\Project\\FP HOMEWORKD\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.8.2\\dataflow-project-0.1.0.0\\build"
    C:\msys64\mingw64\lib

dynamic-library-dirs:
    "C:\\Project\\FP HOMEWORKD\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.8.2\\dataflow-project-0.1.0.0\\build"
    C:\msys64\mingw64\lib

data-dir:
    "C:\\Project\\FP HOMEWORKD\\Haskell-Course-2026\\project\\."

hs-libraries:         HSdataflow-project-0.1.0.0-inplace
include-dirs:         C:\msys64\mingw64\include
depends:
    base-4.19.1.0-6554 mtl-2.3.1-e436 transformers-0.6.1.0-98c8

haddock-interfaces:
    "C:\\Project\\FP HOMEWORKD\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.8.2\\dataflow-project-0.1.0.0\\doc\\html\\dataflow-project\\dataflow-project.haddock"

haddock-html:
    "C:\\Project\\FP HOMEWORKD\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.8.2\\dataflow-project-0.1.0.0\\doc\\html\\dataflow-project"
